// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnExX2Jp0p6vuSVmYMVkiqYBQHTURxXWo',
    appId: '1:240457942587:web:de7313eeac1be513fb7e1e',
    messagingSenderId: '240457942587',
    projectId: 'atalakou-57294',
    authDomain: 'atalakou-57294.firebaseapp.com',
    storageBucket: 'atalakou-57294.appspot.com',
    measurementId: 'G-K4VCF5P5X2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACzDcCxzHs1m9MZc-g2npzDcHMTcJSfqg',
    appId: '1:240457942587:android:4a9ae44ed280ae67fb7e1e',
    messagingSenderId: '240457942587',
    projectId: 'atalakou-57294',
    storageBucket: 'atalakou-57294.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqNzlovb1v76twdVfpld_f8VQEMbFZcTA',
    appId: '1:240457942587:ios:a084d21a5af6d612fb7e1e',
    messagingSenderId: '240457942587',
    projectId: 'atalakou-57294',
    storageBucket: 'atalakou-57294.appspot.com',
    iosBundleId: 'com.atalakou',
  );

}